version: '3.3'

services:
  postgres:
    image: 'postgres:latest'
    container_name: eventcenter_backend
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: user
      POSTGRES_DB: event_center
