version: '3.3'

services:
  postgres:
    image: 'postgres:latest'
    container_name: eventcenter_backend
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${JDBC_DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${JDBC_DATABASE_PASSWORD}
      POSTGRES_DB: event_center
